name: jupyter_dask

channels:
  - conda-forge

dependencies:
  - python=3.9
  - dask[complete]
  - dask-jobqueue
  - jupyterlab>=3
  - dask-labextension
  - jupyterlab-git
  - xarray
  - rioxarray
  - matplotlib 
  - h5netcdf
  - shapely
  - fsspec=2022.8.2
  - zarr
  - pip
  - pip:
    - stac2dcache

